//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels_Resrevation.Resources.Profile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProfileIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotels_Resrevation.Resources.Profile.ProfileIndex", typeof(ProfileIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Facility.
        /// </summary>
        public static string Add_Facility {
            get {
                return ResourceManager.GetString("Add Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All Rooms.
        /// </summary>
        public static string All_Rooms {
            get {
                return ResourceManager.GetString("All Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the image ?!.
        /// </summary>
        public static string Are_you_sure_you_want_to_delete_the_image___ {
            get {
                return ResourceManager.GetString("Are you sure you want to delete the image ?!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Avail {
            get {
                return ResourceManager.GetString("Avail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Rooms.
        /// </summary>
        public static string Available_Rooms {
            get {
                return ResourceManager.GetString("Available Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string Change_your_password {
            get {
                return ResourceManager.GetString("Change your password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Confirm_new_password {
            get {
                return ResourceManager.GetString("Confirm new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Current_password {
            get {
                return ResourceManager.GetString("Current password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Count.
        /// </summary>
        public static string Days_Count {
            get {
                return ResourceManager.GetString("Days Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string End_Date {
            get {
                return ResourceManager.GetString("End Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Get_Started {
            get {
                return ResourceManager.GetString("Get Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel Name.
        /// </summary>
        public static string Hotel_Name {
            get {
                return ResourceManager.GetString("Hotel Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotels.
        /// </summary>
        public static string Hotels {
            get {
                return ResourceManager.GetString("Hotels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review.
        /// </summary>
        public static string Leave_a_review {
            get {
                return ResourceManager.GetString("Leave a review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Profile Image.
        /// </summary>
        public static string Make_Profile_Image {
            get {
                return ResourceManager.GetString("Make Profile Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Rooms.
        /// </summary>
        public static string More_Rooms {
            get {
                return ResourceManager.GetString("More Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string New_Password {
            get {
                return ResourceManager.GetString("New Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Facilties.
        /// </summary>
        public static string No_Facilties {
            get {
                return ResourceManager.GetString("No Facilties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reviews Yet.
        /// </summary>
        public static string No_Reivews_Yet {
            get {
                return ResourceManager.GetString("No Reivews Yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Reservations Yet.
        /// </summary>
        public static string No_Reservations {
            get {
                return ResourceManager.GetString("No Reservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rooms... Create.
        /// </summary>
        public static string NoImages {
            get {
                return ResourceManager.GetString("NoImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Reservations.
        /// </summary>
        public static string Reservation {
            get {
                return ResourceManager.GetString("Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room No.
        /// </summary>
        public static string Room_No {
            get {
                return ResourceManager.GetString("Room No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_Date {
            get {
                return ResourceManager.GetString("Start Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload an Image.
        /// </summary>
        public static string Upload_an_Image {
            get {
                return ResourceManager.GetString("Upload an Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Reviews.
        /// </summary>
        public static string User_Reviews {
            get {
                return ResourceManager.GetString("User Reviews", resourceCulture);
            }
        }
    }
}
