//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotels_Resrevation.Resources.Rooms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoomsIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoomsIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hotels_Resrevation.Resources.Rooms.RoomsIndex", typeof(RoomsIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string Book_Now {
            get {
                return ResourceManager.GetString("Book Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brief Description.
        /// </summary>
        public static string Brief_Description {
            get {
                return ResourceManager.GetString("Brief Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Availability.
        /// </summary>
        public static string Check_Availability {
            get {
                return ResourceManager.GetString("Check Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Room.
        /// </summary>
        public static string Create_Room {
            get {
                return ResourceManager.GetString("Create Room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation From.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Suite.
        /// </summary>
        public static string isSuite {
            get {
                return ResourceManager.GetString("isSuite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Rooms.
        /// </summary>
        public static string No_Rooms {
            get {
                return ResourceManager.GetString("No Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupied.
        /// </summary>
        public static string Occupied {
            get {
                return ResourceManager.GetString("Occupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persons.
        /// </summary>
        public static string Persons {
            get {
                return ResourceManager.GetString("Persons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation_Date.
        /// </summary>
        public static string Reservation_Date {
            get {
                return ResourceManager.GetString("Reservation_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Capacity.
        /// </summary>
        public static string Room_Capacity {
            get {
                return ResourceManager.GetString("Room Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Image.
        /// </summary>
        public static string Room_Image {
            get {
                return ResourceManager.GetString("Room Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room No..
        /// </summary>
        public static string Room_No_ {
            get {
                return ResourceManager.GetString("Room No.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Price for a night.
        /// </summary>
        public static string Room_Price_for_a_night {
            get {
                return ResourceManager.GetString("Room Price for a night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string Rooms {
            get {
                return ResourceManager.GetString("Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReservationTo.
        /// </summary>
        public static string toDate {
            get {
                return ResourceManager.GetString("toDate", resourceCulture);
            }
        }
    }
}
